spring:
  main:
    allow-bean-definition-overriding: false
  application:
    name: SobesCracker
  datasource:
    url: jdbc:postgresql://localhost:5432/sobescracker_db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

        format_sql: true
        show-sql: true
        use_sql_comments: true
        type: trace

server:
  port: 8080

logging:
  level:
    sql: trace
    org.hibernate.orm.jdbc.bind: trace